package com.egtechnologies.sgtapp.domain;
// Generated 09-feb-2018 0:17:04 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * THardware generated by hbm2java
 */
public class THardware implements java.io.Serializable {

    private Integer idHardware;
    private Integer idCompany;
    private Integer idHardwareType;
    private String brand;
    private String model;
    private String serialNumber;
    private Boolean active;
    private Integer createdBy;
    private Date createdDate;
    private Integer modifiedBy;
    private Date modifiedDate;
    private Set<TAssignation> TAssignations = new HashSet<>(0);
    private Set<TInstallation> TInstallations = new HashSet<>(0);

    public THardware() {
    }

    public THardware(Integer idCompany, Integer idHardwareType, String brand, String model, String serialNumber, Boolean active, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate, Set<TAssignation> TAssignations, Set<TInstallation> TInstallations) {
        this.idCompany = idCompany;
        this.idHardwareType = idHardwareType;
        this.brand = brand;
        this.model = model;
        this.serialNumber = serialNumber;
        this.active = active;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
        this.TAssignations = TAssignations;
        this.TInstallations = TInstallations;
    }

    public Integer getIdHardware() {
        return this.idHardware;
    }

    public void setIdHardware(Integer idHardware) {
        this.idHardware = idHardware;
    }

    public Integer getIdCompany() {
        return idCompany;
    }

    public void setIdCompany(Integer idCompany) {
        this.idCompany = idCompany;
    }

    public Integer getIdHardwareType() {
        return idHardwareType;
    }

    public void setIdHardwareType(Integer idHardwareType) {
        this.idHardwareType = idHardwareType;
    }

    public String getBrand() {
        return this.brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public String getSerialNumber() {
        return this.serialNumber;
    }

    public void setSerialNumber(String serialNumber) {
        this.serialNumber = serialNumber;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    public Set<TAssignation> getTAssignations() {
        return this.TAssignations;
    }

    public void setTAssignations(Set<TAssignation> TAssignations) {
        this.TAssignations = TAssignations;
    }

    public Set<TInstallation> getTInstallations() {
        return this.TInstallations;
    }

    public void setTInstallations(Set<TInstallation> TInstallations) {
        this.TInstallations = TInstallations;
    }

}
