package com.egtechnologies.sgtapp.domain;
// Generated 10-ene-2018 4:21:48 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TPassword generated by hbm2java
 */
public class TPassword implements java.io.Serializable {

    private Integer idPassword;
    private Integer idUser;
    private String password;
    private Boolean locked;
    private Date lockedDate;
    private Boolean active;
    private Integer createdBy;
    private Date createdDate;
    private Integer modifiedBy;
    private Date modifiedDate;

    public TPassword() {
    }

    public TPassword(Integer idUser) {
        this.idUser = idUser;
    }

    public TPassword(Integer idUser, String password, Boolean locked, Date lockedDate, Boolean active, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
        this.idUser = idUser;
        this.password = password;
        this.locked = locked;
        this.lockedDate = lockedDate;
        this.active = active;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }

    public Integer getIdPassword() {
        return this.idPassword;
    }

    public void setIdPassword(Integer idPassword) {
        this.idPassword = idPassword;
    }

    public Integer getIdUser() {
        return this.idUser;
    }

    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getLocked() {
        return this.locked;
    }

    public void setLocked(Boolean locked) {
        this.locked = locked;
    }

    public Date getLockedDate() {
        return this.lockedDate;
    }

    public void setLockedDate(Date lockedDate) {
        this.lockedDate = lockedDate;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

}
