package com.egtechnologies.sgtapp.domain;
// Generated 10-ene-2018 4:21:48 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TRights generated by hbm2java
 */
public class TRights implements java.io.Serializable {

    private Integer idRights;
    private Integer idFacilities;
    private Integer idRole;
    private Boolean active;
    private Integer createdBy;
    private Date createdDate;
    private Integer modifiedBy;
    private Date modifiedDate;

    public TRights() {
    }

    public TRights(Integer idFacilities, Integer idRole) {
        this.idFacilities = idFacilities;
        this.idRole = idRole;
    }

    public TRights(Integer idFacilities, Integer idRole, Boolean active, Integer createdBy, Date createdDate, Integer modifiedBy, Date modifiedDate) {
        this.idFacilities = idFacilities;
        this.idRole = idRole;
        this.active = active;
        this.createdBy = createdBy;
        this.createdDate = createdDate;
        this.modifiedBy = modifiedBy;
        this.modifiedDate = modifiedDate;
    }

    public Integer getIdRights() {
        return this.idRights;
    }

    public void setIdRights(Integer idRights) {
        this.idRights = idRights;
    }

    public Integer getIdFacilities() {
        return this.idFacilities;
    }

    public void setIdFacilities(Integer idFacilities) {
        this.idFacilities = idFacilities;
    }

    public Integer getIdRole() {
        return this.idRole;
    }

    public void setIdRole(Integer idRole) {
        this.idRole = idRole;
    }

    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Integer getModifiedBy() {
        return this.modifiedBy;
    }

    public void setModifiedBy(Integer modifiedBy) {
        this.modifiedBy = modifiedBy;
    }

    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

}
